### ISSUE TITLE
apply a function to each series in a dataframe

### ISSUE THREAD

**Issue by richardhundt** [StratoDem/pandas-js#50]
Hi there,

apply() and transform() seem to be missing, or I'm not looking hard enough. It seems like the most obvious and general thing I could want to do: apply a function to each row of my data, so I'm pretty sure I've just missed the api for that somehow. Any tips?

**Comment by mritchie712** [comment]
[Check out](https://stratodem.github.io/pandas.js-docs/#code-dataframe-iterrows-code) 
 `iterrows`

**Comment by richardhundt** [comment]
thanks, not ideal, but that's probably a javascript limitation - in pandas I can `df['foo'] = df.apply(func, axis=1)` which is nice
